Repository RocketChat/docs, pull requests merged in 2018-06, with the labels that each got.

#785 [WIP][NEW] Add supported version of the servers from the Mobile Apps
  _data/toc.yml
  contributing/documentation/documentation-map/README.md
  developer-guides/mobile-apps/servers-support/README.md
Labels: Android, iOS

#792 [DOCS] Update documentation related to FCM support on the native Android application
  administrator-guides/notifications/push-notifications/README.md
Labels: Android

#791 [DOCS] Update required version to latest Android release & future releases
  developer-guides/mobile-apps/supported-servers-versions/README.md
Labels: Android, iOS

#793 [FIX] Fix Payload list that was missing an argument in REST room.saveNotifications
  developer-guides/rest-api/rooms/savenotification/README.md
Labels: API

#805 [FIX] Fix /users.updateOwnBasicInfo, add missing customFields inside payload
  developer-guides/rest-api/users/updateownbasicinfo/README.md
Labels: API

#809 [NEW] Add docs for groups.roles and channels.roles REST endpoints
  _data/toc.yml
  contributing/documentation/documentation-map/README.md
  developer-guides/rest-api/README.md
  developer-guides/rest-api/channels/README.md
  developer-guides/rest-api/channels/roles/README.md
  developer-guides/rest-api/groups/README.md
  developer-guides/rest-api/groups/roles/README.md
Labels: API

#777 [NEW] Add permissions.list and permissions.update, and deprecate permissions
  _data/toc.yml
  contributing/documentation/documentation-map/README.md
  developer-guides/deprecation/README.md
  developer-guides/rest-api/README.md
  developer-guides/rest-api/permissions/README.md
  developer-guides/rest-api/permissions/list/README.md
  developer-guides/rest-api/permissions/update/README.md
Labels: Waiting Pull Request

#772 [NEW] Add channels.setDefault
  _data/toc.yml
  contributing/documentation/documentation-map/README.md
  developer-guides/rest-api/README.md
  developer-guides/rest-api/channels/README.md
  developer-guides/rest-api/channels/setdefault/README.md
Labels: Waiting Pull Request
