Repository RocketChat/docs, pull requests merged in 2020-02, with the labels that each got.

#1581 [GSoC 2020] Add Omnichannel project ideas
  contributing/google-summer-of-code-2020/README.md
Labels: omnichannel

#1589 [FIX] WhatsApp doc page
  _data/toc.yml
  administrator-guides/livechat/whatsapp-twilio/README.md
Labels: omnichannel

#1573 Add warning for user's identity validation
  developer-guides/rest-api/chat/postmessage/README.md
  developer-guides/rest-api/chat/sendmessage/README.md
Labels: API

#1556 Show top navbar in embedded layout setting.
  developer-guides/embedded-layout/README.md
Labels: Waiting Pull Request
